---
default_target:
  - {name: configure, target: default}
  - {name: build, target: default}
  - {name: clean, target: default}
  - {name: rebuild, target: default}
  - {name: run, target: default}
---
targets:
  - name: default 
    target_template: makefile
    output_file_name: larix_dummy_package
    source_files:
      - src/*.c
